# meta
author:      "Mike Vardy"
baseurl:     "/bootstrap-4-kitchen-sink"
description: "Kitchen Sink for Bootstrap 4"
title:       "Bootstrap 4 Kitchen Sink"
url:         "https://mike-at-august.github.io/bootstrap-4-kitchen-sink"

gems:
  - jekyll-tidy

# build
exclude:
  - README.md
